# Generated by Django 5.0.6 on 2024-06-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(choices=[('Birthday', 'Birthday'), ('Baby Shower', 'Baby Shower'), ('Gender Reveal', 'Gender Reveal'), ('Decor', 'Decor'), ('Toys', 'Toys'), ('Board Games', 'Board Games')], max_length=50)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
                ('price', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
